print("Welcome to the Band Name Generator.")
print("What's the name of the city you grew up in?")
YOURNAME = input()
print("What is your pet's name?")
PETNAME = input()
print("Your band's name could be " + YOURNAME + " " + PETNAME)