print("Welcome to the Band Name Generator.")
print("What's the name of the city you grew up in?")
a = input()
print("What is your pet's name?")
b = input()
print("Your band's name could be " + a + " " + b)